# configs/datasets/inpe/area_queimada_focos1km.yml
id: inpe_area_queimada_focos1km
title: "INPE - √Årea Queimada - FOCOS 1km (TIF)"
source_url: "https://dataserver-coids.inpe.br/queimadas/queimadas/area_queimada/FOCOS1km/tif/"
bucket_prefix: inpe/area_queimada/focos1km
include_meta: false